language: python
python:
  - "2.7"

install:
  - "pip install -r requirements.txt"

script:
  - "python bot.py"

after_success:
  - "coveralls"
  
env:
  - PYTHONPATH=.

notifications:
  irc:
    channels:
      - "irc.rizon.net#w24bot"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}) %{author}: %{message} - %{build_url}"
  on_failure: always
  on_success: change
  skip_join: true
