#!/bin/bash
echo "wbot, a Python IRC bot, forked from UguuBot."
echo "https://github.com/mrw24/wbot               "
echo "Need help? Join #W24bot on irc.rizon.net    "


locatefiles() {
    botfile="/bot.py"
    botfile=$(pwd)$botfile
    logfile="/bot.log"
    logfile=$(pwd)$logfile
}

running() {
    if [[ $(ps aux|grep bot.py|grep -v grep|grep -v daemon|grep -v SCREEN) != "" ]]; then
        true
    else
        false
    fi
}

checkbackend() {
        if dpkg -l| grep ^ii|grep daemon|grep 'turns other' > /dev/null; then
            backend="daemon"
        elif dpkg -l| grep ^ii|grep screen|grep 'terminal multi' > /dev/null; then
            backend="screen"
        else
            backend="manual"
        fi
    return 0
}

setcommands() {
    status() {
        if running; then
            echo "wbot is currently running!"
        else
            echo "wbot is currently not running!"
        fi
    }
    clear() {
        : > $logfile
    }
    if [ "$backend" == "daemon" ]; then
        start() {
            daemon -r -n uguubot -O $logfile python $botfile
        }
        stop() {
            daemon -n uguubot --stop
        }
    elif [ "$backend" == "screen" ]; then
        start() {
            screen -d -m -S uguubot -t uguubot python $botfile > $logfile 2>&1
        }
        stop() {
            pid=`ps ax|grep -v grep|grep python|grep -v SCREEN|grep $botfile|awk '{print $1}'`
            kill $pid
        }
    elif [ "$backend" == "manual" ]; then
        start() {
            $botfile
        }
        stop() {
            pid=`ps ax|grep -v grep|grep python|grep $botfile|awk '{print $1}'`
            kill $pid
        }
    fi
}

processargs() {
    case $1 in
        start|-start|--start)
            if running; then
                echo "Cannot start! Bot is already running!"
                exit 1
            else
                echo "Starting wbot... ($backend)"
                start
            fi
        ;;
        stop|-stop|--stop)
            if running; then
                echo "Stopping wbot... ($backend)"
                stop
            else
                echo "Error: Could not stop. wbot isn't running at the moment!"
                exit 1
            fi
        ;;
        restart|-restart|--restart)
            if running; then
                echo "Restarting wbot... ($backend)"
                stop
                sleep 3
                start
            else
                echo "Error: Could not restart! wbot isn't running at the moment!"
                exit 1
            fi
        ;;
        clear|-clear|--clear)
            echo "Clearing logs..."
            clear
        ;;
        status|-status|--status)
            status
        ;;
        *)  
            usage="usage: ./uguubot {start|stop|restart|clear|status}"
            echo $usage
        ;;
    esac
}

main() {
    locatefiles
    checkbackend
    setcommands
    processargs $1
}

main $*
exit 0
